---
- name: Update Servers
  hosts: localhost
  become: yes  

  tasks:
    - name: Display no update needed
      debug:
        msg: "{{ hostvars | length  }}"
      delegate_to: localhost 
 
    - name: Display no update needed
      debug:
        msg: "{{ groups['all'] | length }}"
        
