---
- name: Check last reboot time on servers
  hosts: balancers # Replace with your server group
  gather_facts: yes
  tags: datatype

  tasks:

    - name: Check OS and its distribution version
      debug: 
        msg: "The OS is {{ ansible_facts['distribution'] }} and version is {{ ansible_facts['distribution_version'] }}"
  
    - name: Get uptime information
      command: last reboot
      register: uptime_output
      changed_when: false  # This command does not change the system state

    - name: Extract last reboot time
      set_fact:
        last_reboot_info: "{{ uptime_output.stdout_lines[0] }}"
      when: uptime_output.rc == 0

    - name: Display last reboot time
      debug:
        var: last_reboot_info
      when: uptime_output.rc == 0
